package cm.fwi.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DAOUtil {

    public static PreparedStatement initPreparedStatement( Connection connection, String query,
            boolean autoGeneratedKey, Object... objects ) throws SQLException {

        PreparedStatement preparedStatement = connection.prepareStatement( query,
                autoGeneratedKey ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS );
        for ( int i = 0; i < objects.length; i++ ) {
            preparedStatement.setObject( i + 1, objects[i] );
        }
        return preparedStatement;
    }

    public static void closeResource( ResultSet resultSet ) {

        if ( resultSet != null ) {
            try {
                resultSet.close();
            } catch ( SQLException e ) {
                e.printStackTrace();
            }
        }
    }

    public static void closeResource( PreparedStatement preparedStatement ) {

        if ( preparedStatement != null ) {
            try {
                preparedStatement.close();
            } catch ( SQLException e ) {
                e.printStackTrace();
            }
        }
    }

    public static void closeResource( Connection connection ) {

        if ( connection != null ) {
            try {
                connection.close();
            } catch ( SQLException e ) {
                e.printStackTrace();
            }
        }
    }

    public static void closeResources( ResultSet resultSet, PreparedStatement preparedStatement,
            Connection connection ) {

        closeResource( resultSet );
        closeResource( preparedStatement );
        closeResource( connection );
    }
    
    public static void closeResources( ResultSet resultSet, PreparedStatement preparedStatement ) {

        closeResource( resultSet );
        closeResource( preparedStatement );
    }

    public static void closeResources( PreparedStatement preparedStatement, Connection connection ) {

        closeResource( preparedStatement );
        closeResource( connection );
    }
}
